### ISSUE TITLE
Sudospawner with jupyterhub 0.8.0

### ISSUE THREAD

**Issue by csghuser** [jupyterhub/sudospawner#44]
Has anyone had any issues with using sudospawner with version 0.8.0 of jupyterhub?

I can't see any specific errors in the log, other than it mentions that it took too long for the session to spawn. It was all working fine with 0.7.2.

**Comment by lbiemans** [comment]
@csghuser I also have problems with jupyterhub 0.8.0 and sudospawner 0.5.0 / 0.6.0.dev0. The error I get is: 

[E 2017-10-06 09:17:16.164 JupyterHub gen:914] Exception in Future <tornado.concurrent.Future object at 0x7fb3b1a9b7f0> after timeout
    Traceback (most recent call last):
      File "/usr/local/lib/python3.5/dist-packages/tornado/gen.py", line 910, in error_callback
        future.result()
      File "/usr/local/lib/python3.5/dist-packages/jupyterhub/handlers/base.py", line 444, in finish_user_spawn
        yield spawn_future
      File "/usr/local/lib/python3.5/dist-packages/jupyterhub/user.py", line 476, in spawn
        raise e
      File "/usr/local/lib/python3.5/dist-packages/jupyterhub/user.py", line 450, in spawn
        resp = yield server.wait_up(http=True, timeout=spawner.http_timeout)
      File "/usr/local/lib/python3.5/dist-packages/jupyterhub/utils.py", line 180, in wait_for_http_server
        timeout=timeout
      File "/usr/local/lib/python3.5/dist-packages/jupyterhub/utils.py", line 135, in exponential_backoff
        raise TimeoutError(fail_message)
    TimeoutError: Server at http://servername:40759/user/lbiemans/ didn't respond in 30 seconds
    
[E 2017-10-06 09:17:16.166 JupyterHub gen:914] Exception in Future <tornado.concurrent.Future object at 0x7fb3b1a9b7f0> after timeout
    Traceback (most recent call last):
      File "/usr/local/lib/python3.5/dist-packages/tornado/gen.py", line 910, in error_callback
        future.result()
      File "/usr/local/lib/python3.5/dist-packages/jupyterhub/handlers/base.py", line 444, in finish_user_spawn
        yield spawn_future
      File "/usr/local/lib/python3.5/dist-packages/jupyterhub/user.py", line 476, in spawn
        raise e
      File "/usr/local/lib/python3.5/dist-packages/jupyterhub/user.py", line 450, in spawn
        resp = yield server.wait_up(http=True, timeout=spawner.http_timeout)
      File "/usr/local/lib/python3.5/dist-packages/jupyterhub/utils.py", line 180, in wait_for_http_server
        timeout=timeout
      File "/usr/local/lib/python3.5/dist-packages/jupyterhub/utils.py", line 135, in exponential_backofmyserver
        raise TimeoutError(fail_message)
    TimeoutError: Server at http://servername:40759/user/lbiemans/ didn't respond in 30 seconds
    
[E 2017-10-06 09:17:16.454 JupyterHub base:709] Preventing implicit spawn for lbiemans because last spawn failed: Server at http://myserver:40759/user/lbiemans/ didn't respond in 30 seconds
[E 2017-10-06 09:17:16.454 JupyterHub web:1590] Uncaught exception GET /hub/user/lbiemans/ (::ffff:137.56.246.142)
    HTTPServerRequest(protocol='http', host='myserver..local', method='GET', uri='/hub/user/lbiemans/', version='HTTP/1.1', remote_ip='::ffff:137.56.246.142', headers={'X-Forwarded-Proto': 'http', 'Dnt': '1', 'If-None-Match': '"ffb1b54e48e4c193a5ea828676c52da54457a535-gzip"', 'Accept-Encoding': 'gzip, deflate, br', 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:55.0) Gecko/20100101 Firefox/55.0', 'Cookie': 'jupyter-hub-token="2|1:0|10:1507273335|17:jupyter-hub-token|44:NjJhMTRjYWEwN2JlNGU5NDllNDQzYzRiYjk0OWU2MGU=|9d6ae560fa2a95afe99eff94909f984aa18f3d18e310202e8849c79c3e8be8cc"; MOD_AUTH_CAS_S=4a787fbce3b829d703ff26109379597b', 'X-Forwarded-For': '137.56.126.164,::ffff:137.56.246.142', 'Host': 'myserver..local', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'Accept-Language': 'en-US,en;q=0.5', 'Cas-User': 'lbiemans', 'Connection': 'close', 'Upgrade-Insecure-Requests': '1', 'X-Forwarded-Server': 'myserver..local', 'X-Forwarded-Port': '80', 'Referer': 'https://myserver..local/hub/home', 'Cache-Control': 'max-age=0', 'X-Forwarded-Host': 'myserver..local'})
    Traceback (most recent call last):
      File "/usr/local/lib/python3.5/dist-packages/tornado/web.py", line 1511, in _execute
        result = yield result
      File "/usr/local/lib/python3.5/dist-packages/jupyterhub/handlers/base.py", line 710, in get
        raise spawner._spawn_future.exception()
      File "/usr/local/lib/python3.5/dist-packages/tornado/gen.py", line 910, in error_callback
        future.result()
      File "/usr/local/lib/python3.5/dist-packages/jupyterhub/handlers/base.py", line 444, in finish_user_spawn
        yield spawn_future
      File "/usr/local/lib/python3.5/dist-packages/jupyterhub/user.py", line 476, in spawn
        raise e
      File "/usr/local/lib/python3.5/dist-packages/jupyterhub/user.py", line 450, in spawn
        resp = yield server.wait_up(http=True, timeout=spawner.http_timeout)
      File "/usr/local/lib/python3.5/dist-packages/jupyterhub/utils.py", line 180, in wait_for_http_server
        timeout=timeout
      File "/usr/local/lib/python3.5/dist-packages/jupyterhub/utils.py", line 135, in exponential_backoff
        raise TimeoutError(fail_message)
    TimeoutError: Server at http://servername:40759/user/lbiemans/ didn't respond in 30 seconds

**Comment by csghuser** [comment]
@lbiemans Yep those are the same errors I'm seeing. 

Have you managed to get it working?

**Comment by lbiemans** [comment]
@csghuser, tried some things but unfortunately none of theme work.

**Comment by glampr** [comment]
Same issue here, downgrading JupyterHub to 0.7.2 seems to work.

**Comment by minrk** [comment]
I think I've figured this out. If you set `c.Spawner.ip = '127.0.0.1'` in your config, does it work?

I'll have a PR to sudospawner fixing the defaults shortly.

**Comment by minrk** [comment]
#45 should fix this. We will release 0.5.1 soon after that is merged.

**Comment by minrk** [comment]
0.5.1 is out with the fix

**Comment by lbiemans** [comment]
@minrk didn't have any time to test it until today, but my test server seems to be running like a charm again. Thanks for the great work!
