### ISSUE TITLE
One user login to jupyterhub but others get internal server error.

### ISSUE THREAD

**Issue by frouzbeh** [jupyterhub/sudospawner#51]
Hi,

I'm new in this area and trying to install jupyterhub using sudospawner on my local machine to see how it works. Everything works fine for one user (the one I installed everything by that) but for other users I'm getting 500 internal server error.  It seems there is a permission issue, but I tried every solution I've found to fix it but nothing has worked. 
Ubuntu 16.4
Jupyterhub 0.9.0.b1

Any idea what should I do?
I would be happy to give more information if needed. 

Thanks,

**Comment by minrk** [comment]
Please include the output from jupyterhub when the failure occurs.

When it works for one user and not others, most often the issue is one of permissions and/or PATH. All users must be able to launch the `jupyterhub-singleuser` entrypoint and import all of the modules in that Python environment. This generally means read and execute permissions on the environment.

Typically, JupyterHub should be installed in a shared, system-wide installation, e.g. default /usr/local, or a dedicated env somewhere that should not be in anyone's home directory.

One way to test this is:

    sudo -u some-other-user /path/to/jupyterhub-singleuser -h

It should show you the help output and not any errors about permissions.

**Comment by frouzbeh** [comment]
Thank you for the response, 
Here is the log when user test tries to login:

[I 2018-05-25 09:47:31.299 JupyterHub app:988] Loading cookie_secret from /home/fatemeh/jupyterhub/jupyterhub_cookie_secret
[I 2018-05-25 09:47:31.310 JupyterHub proxy:429] Generating new CONFIGPROXY_AUTH_TOKEN
[W 2018-05-25 09:47:31.313 JupyterHub configurable:168] Config option `delete_invalid_users` not recognized by `PAMAuthenticator`.
[I 2018-05-25 09:47:31.331 JupyterHub app:1162] Not using whitelist. Any authenticated user will be allowed.
[W 2018-05-25 09:47:31.341 JupyterHub app:1463] Deleting OAuth client jupyterhub-user-fatemeh
[W 2018-05-25 09:47:31.344 JupyterHub app:1463] Deleting OAuth client jupyterhub-user-test
[I 2018-05-25 09:47:31.359 JupyterHub app:1760] Hub API listening on http://127.0.0.1:8081/hub/
[W 2018-05-25 09:47:31.360 JupyterHub proxy:481] Running JupyterHub without SSL.  I hope there is SSL termination happening somewhere else...
[I 2018-05-25 09:47:31.360 JupyterHub proxy:483] Starting proxy @ http://192.168.56.1:8000
09:47:31.480 - info: [ConfigProxy] Proxying http://192.168.56.1:8000 to (no default)
09:47:31.482 - info: [ConfigProxy] Proxy API at http://127.0.0.1:8001/api/routes
[I 2018-05-25 09:47:31.813 JupyterHub proxy:299] Checking routes
[I 2018-05-25 09:47:31.814 JupyterHub proxy:368] Adding default route for Hub: / => http://127.0.0.1:8081
09:47:31.814 - info: [ConfigProxy] 200 GET /api/routes 
09:47:31.860 - info: [ConfigProxy] Adding route / -> http://127.0.0.1:8081
09:47:31.862 - info: [ConfigProxy] 201 POST /api/routes/ 
[I 2018-05-25 09:47:31.863 JupyterHub app:1817] JupyterHub is now running at http://192.168.56.1:8000
[I 2018-05-25 09:47:41.674 JupyterHub base:470] User logged in: test
[I 2018-05-25 09:47:41.675 JupyterHub log:158] 302 POST /hub/login?next= -> /user/test/ (test@192.168.56.1) 17.88ms
[I 2018-05-25 09:47:41.681 JupyterHub log:158] 302 GET /user/test/ -> /hub/user/test/ (@192.168.56.1) 0.50ms
sh: 1: cannot create /run/motd.dynamic.new: Permission denied

The programs included with the Ubuntu system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Ubuntu comes with ABSOLUTELY NO WARRANTY, to the extent permitted by
applicable law.


The programs included with the Ubuntu system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Ubuntu comes with ABSOLUTELY NO WARRANTY, to the extent permitted by
applicable law.

[W 2018-05-25 09:47:41.795 JupyterHub auth:642] Failed to open PAM session for test: [PAM Error 14] Cannot make/remove an entry for the specified session
[W 2018-05-25 09:47:41.795 JupyterHub auth:643] Disabling PAM sessions from now on.
here ['sudo', '-u', 'test']
Traceback (most recent call last):
  File "/usr/local/bin/sudospawner", line 4, in <module>
    __import__('pkg_resources').require('sudospawner==0.6.0.dev0')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2927, in <module>
    @_call_aside
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2913, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2940, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 635, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 943, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 829, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'notebook' distribution was not found and is required by sudospawner
[E 2018-05-25 09:47:42.003 JupyterHub spawner:84] Failed to get JSON result from mediator: ''
[E 2018-05-25 09:47:42.003 JupyterHub user:472] Unhandled error starting test's server: substring not found
[E 2018-05-25 09:47:42.029 JupyterHub spawner:709] post_stop_hook failed with exception: <sudospawner.spawner.SudoSpawner object at 0x7f7617e58fd0>
    Traceback (most recent call last):
      File "/home/fatemeh/jupyterhub/jupyterhub/spawner.py", line 707, in run_post_stop_hook
        return self.post_stop_hook(self)
    TypeError: 'NoneType' object is not callable
    
[E 2018-05-25 09:47:42.031 JupyterHub web:1621] Uncaught exception GET /hub/user/test/ (192.168.56.1)
    HTTPServerRequest(protocol='http', host='192.168.56.1:8000', method='GET', uri='/hub/user/test/', version='HTTP/1.1', remote_ip='192.168.56.1')
    Traceback (most recent call last):
      File "/home/fatemeh/.local/lib/python3.5/site-packages/tornado/web.py", line 1543, in _execute
        result = yield result
      File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
        raise self._exception
      File "/usr/lib/python3.5/asyncio/tasks.py", line 241, in _step
        result = coro.throw(exc)
      File "/home/fatemeh/jupyterhub/jupyterhub/handlers/base.py", line 953, in get
        await self.spawn_single_user(user)
      File "/home/fatemeh/jupyterhub/jupyterhub/handlers/base.py", line 642, in spawn_single_user
        await gen.with_timeout(timedelta(seconds=self.slow_spawn_timeout), finish_spawn_future)
      File "/usr/lib/python3.5/asyncio/futures.py", line 361, in __iter__
        yield self  # This tells Task to wait for completion.
      File "/usr/lib/python3.5/asyncio/tasks.py", line 296, in _wakeup
        future.result()
      File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
        raise self._exception
      File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
        result = coro.send(None)
      File "/home/fatemeh/jupyterhub/jupyterhub/handlers/base.py", line 597, in finish_user_spawn
        await spawn_future
      File "/home/fatemeh/jupyterhub/jupyterhub/user.py", line 484, in spawn
        raise e
      File "/home/fatemeh/jupyterhub/jupyterhub/user.py", line 404, in spawn
        url = await gen.with_timeout(timedelta(seconds=spawner.start_timeout), f)
      File "/usr/lib/python3.5/asyncio/futures.py", line 361, in __iter__
        yield self  # This tells Task to wait for completion.
      File "/usr/lib/python3.5/asyncio/tasks.py", line 296, in _wakeup
        future.result()
      File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
        raise self._exception
      File "/home/fatemeh/jupyterhub/sudospawner/sudospawner/spawner.py", line 93, in start
        reply = yield self.do(action='spawn', args=self.get_args(), env=self.get_env())
      File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
        raise self._exception
      File "/home/fatemeh/jupyterhub/sudospawner/sudospawner/spawner.py", line 81, in do
        data_str = data_str[data_str.index('{'):data_str.rindex('}')+1]
    ValueError: substring not found
    
[E 2018-05-25 09:47:42.080 JupyterHub log:150] {
      "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
      "Accept-Encoding": "gzip, deflate",
      "X-Forwarded-Port": "8000",
      "X-Forwarded-For": "192.168.56.1",
      "Upgrade-Insecure-Requests": "1",
      "X-Forwarded-Proto": "http",
      "Referer": "http://192.168.56.1:8000/hub/login",
      "Connection": "close",
      "Accept-Language": "en-GB,en;q=0.5",
      "Cookie": "jupyterhub-hub-login=\"2|1:0|10:1527256061|20:jupyterhub-hub-login|44:YTZmZDc2OWMyZmNmNDgyNzk0NGM3MmJiM2MxNWIxZTU=|27089f4ae37e9903d090cd37b285585632e5f5e217324ddd494c64cd0e3bde45\"; _xsrf=2|0637f70a|be46b6c98aa82d32a2947955876744db|1525883715; jupyterhub-session-id=639ec2f9562740be8ca66318f46b5a9a",
      "User-Agent": "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:60.0) Gecko/20100101 Firefox/60.0",
      "X-Forwarded-Host": "192.168.56.1:8000",
      "Host": "192.168.56.1:8000"
    }
[E 2018-05-25 09:47:42.080 JupyterHub log:158] 500 GET /hub/user/test/ (test@192.168.56.1) 379.21ms


Also, when I run the command "sudo -u some-other-user /path/to/jupyterhub-singleuser -h" for this user I'm getting this error:

Traceback (most recent call last):
  File "/usr/local/bin/jupyterhub-singleuser", line 4, in <module>
    __import__('pkg_resources').require('jupyterhub==0.9.0b1')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2927, in <module>
    @_call_aside
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2913, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2940, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 635, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 943, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 829, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'prometheus_client>=0.0.21' distribution was not found and is required by jupyterhub


All jupyterhub, sudospawner and jupyterhub-single user are in /usr/local/bin/ path. and here is the permissions:
-rwxr-xr-x 1 root root 222 May 11 22:49 /usr/local/bin/jupyter
-rwxr-xr-x 1 root root 236 May 11 22:49 /usr/local/bin/jupyter-bundlerextension
-rwxr-xr-x 1 root root 289 May 17 18:15 /usr/local/bin/jupyterhub
-rwxr-xr-x 1 root root 311 May 17 18:15 /usr/local/bin/jupyterhub-singleuser
-rwxr-xr-x 1 root root 226 May 11 22:49 /usr/local/bin/jupyter-kernel
-rwxr-xr-x 1 root root 264 May 11 22:49 /usr/local/bin/jupyter-kernelspec
-rwxr-xr-x 1 root root 222 May 11 22:49 /usr/local/bin/jupyter-migrate
-rwxr-xr-x 1 root root 224 May 11 22:49 /usr/local/bin/jupyter-nbconvert
-rwxr-xr-x 1 root root 223 May 11 22:49 /usr/local/bin/jupyter-nbextension
-rwxr-xr-x 1 root root 222 May 11 22:49 /usr/local/bin/jupyter-notebook
-rwxr-xr-x 1 root root 243 May 11 22:49 /usr/local/bin/jupyter-run
-rwxr-xr-x 1 root root 227 May 11 22:49 /usr/local/bin/jupyter-serverextension
-rwxr-xr-x 1 root root 227 May 11 22:49 /usr/local/bin/jupyter-troubleshoot
-rwxr-xr-x 1 root root 255 May 11 22:49 /usr/local/bin/jupyter-trust
-rwxr-xr-x 1 root root 315 May 17 18:15 /usr/local/bin/sudospawner

**Comment by frouzbeh** [comment]
I also changed the group of jupyter files in /usr/local/bin to jupyterhub (which is the group of jupyterhub users), but still getting error 500.

-rwxr-xr-x 1 root jupyterhub 222 May 11 22:49 /usr/local/bin/jupyter
-rwxr-xr-x 1 root jupyterhub 236 May 11 22:49 /usr/local/bin/jupyter-bundlerextension
-rwxr-xr-x 1 root jupyterhub 289 May 17 18:15 /usr/local/bin/jupyterhub
-rwxr-xr-x 1 root jupyterhub 311 May 17 18:15 /usr/local/bin/jupyterhub-singleuser
-rwxr-xr-x 1 root jupyterhub 226 May 11 22:49 /usr/local/bin/jupyter-kernel
-rwxr-xr-x 1 root jupyterhub 264 May 11 22:49 /usr/local/bin/jupyter-kernelspec
-rwxr-xr-x 1 root jupyterhub 222 May 11 22:49 /usr/local/bin/jupyter-migrate
-rwxr-xr-x 1 root jupyterhub 224 May 11 22:49 /usr/local/bin/jupyter-nbconvert
-rwxr-xr-x 1 root jupyterhub 223 May 11 22:49 /usr/local/bin/jupyter-nbextension
-rwxr-xr-x 1 root jupyterhub 222 May 11 22:49 /usr/local/bin/jupyter-notebook
-rwxr-xr-x 1 root jupyterhub 243 May 11 22:49 /usr/local/bin/jupyter-run
-rwxr-xr-x 1 root jupyterhub 227 May 11 22:49 /usr/local/bin/jupyter-serverextension
-rwxr-xr-x 1 root jupyterhub 227 May 11 22:49 /usr/local/bin/jupyter-troubleshoot
-rwxr-xr-x 1 root jupyterhub 255 May 11 22:49 /usr/local/bin/jupyter-trust
-rwxr-xr-x 1 root jupyterhub 315 May 17 18:15 /usr/local/bin/sudospawner

**Comment by minrk** [comment]
Try checking the permissions in the dist-packages and/or site-packages directories. When you import the `notebook` package as the user that works, check that the permissions on that package make it readable by all users.
