### ISSUE TITLE
ModuleNotFoundError: No module named 'pipes'

### ISSUE THREAD

**Issue by UlyssesZh** [jupyterhub/sudospawner#78]
### Bug description

Python 3.13 removed the module `pipes` from standard library. See [PEP 594](https://peps.python.org/pep-0594/#pipes).

### How to reproduce

Use SudoSpawner with Python 3.13.

#### Expected behaviour

Runs fine.

#### Actual behaviour

```console
Traceback (most recent call last):
  File "/usr/bin/sudospawner", line 3, in <module>
    from sudospawner import mediator
  File "/usr/lib/python3.13/site-packages/sudospawner/mediator.py", line 26, in <module>
    import pipes
ModuleNotFoundError: No module named 'pipes'
```

### Your personal set up

 - OS: Arch Linux
 
 - Version(s):  JupyterHub 5.2.1, Python 3.13

**Comment by chippey** [comment]
Just adding in as another user getting bit by this.  Setting up a JupyterHub testbed on Rocky 9.6, via conda which defaulted to Python 3.13

**Comment by consideRatio** [comment]
This is now resolved in the main branch by excellent work by @urlicht and @ken-lauer!! Thank you!!!
